port: "8080"
db_user: "postgres"
db_password: "postgres"
db_host: "localhost"
db_port: "5432"
db_name: "fishing_db"
fishing_methods:
  - "спиннинг"
  - "джиг"
  - "микроджиг"
  - "мормышинг"
  - "троллинг"
  - "поплавочная удочка"
  - "донка"
  - "жерлица"
  - "кружки"
  - "отвесное блеснение"
  - "квок"
  - "мормышка"
  - "отводной поводок"
fish_species:
  - "щука"
  - "окунь"
  - "судак"
  - "карп"
  - "сом европейский"
  - "налим"
  - "жерех"
  - "карась"
  - "плотва"
  - "красноперка"
  - "лещ"
  - "пескарь"
  - "теляпия"
  - "форель"
  - "осетр"
  - "голавль"
  - "ротан"
  - "бычок"
  - "уклейка"
  - "хариус"
  - "сом африканский"
  - "язь"
  - "стерлядь"
baits:
  - "виброхвост"
  - "блесна вращающаяся"
  - "твистер"
  - "воблер"
  - "блесна колеблющаяся"
  - "спиннербейт"
  - "мормышка"
  - "другой силикон"
  - "магот"
  - "червяк"
  - "бойл"
  - "селедка"
  - "кукуруза"
  - "опарыш"
  - "хлеб"
  - "тесто"
  - "манка"
  - "живец"
  - "виб"